a = input('Digite Algo: ')
print(f'O tipo primitivo desse valor é: ', type(a))
print(f'Só tem espaços?  {a.isspace()} ')
print(f'Isso é um numero?  {a.isnumeric()} ')
print(f'Isso é Alfabético? {a.isalpha()} ')
print(f'Isso é Alfanumerico? {a.isnumeric()} ')
print(f'Está em letras maiúsculas? {a.isupper()} ')
print(f'Está em letras minúsculas? {a.islower()} ')
print(f'Está capitalizada? {a.istitle()} ')
